# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
            - php
        networks:
            - laravel
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: mnhsenrollment
            MYSQL_USER: mnhs
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql    
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
    ssms-app:
        build:
            context: ./docker/app
        # args:
        #     uid: ${UID}
        container_name: ssms-app
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        volumes:
            - ./src:/var/www/html
        ports:
            # - "${HOST_PORT}:80"
            - "6001:6001"
        links:
            # - ssms-redis
            - ssms-sockets
        networks:
            backend:
                aliases:
                    - ssms-app
    ssms-sockets:
        build:
            context: ./docker/websockets
        container_name: ssms-sockets
        volumes:
            - ./src:/var/www/html
        ports:
            - "6001:6001"
        networks:
            backend:
                aliases:
                    - ssms-sockets
networks:
    laravel:
    backend:
